add_newline = true
command_timeout = 500

format = """
╭─$username\
$directory\
$git_branch\
$git_status\
$nodejs\
$python\
$battery\
${custom.power}\
${custom.net}\
$time[➤](bold white)\
$line_break\
╰─$character"""

[custom.power]
command = 'p=$(powerprofilesctl get); case "$p" in power-saver) printf "\033[1;32m󰌪\033[0m";; performance) printf "\033[1;31m󰓅\033[0m";; *) printf "\033[1;34m󰊚\033[0m";; esac'
format   = '[\[](dimmed) $output [\]](dimmed) '
shell    = "bash"
style    = "bold cyan"
unsafe_no_escape = true
when     = true

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[❯](bold red)"

[username]
show_always = true
style_user = "bold blue"
style_root = "bold red"
format = '[\[](dimmed) [$user]($style) [\]](dimmed) '

[directory]
truncation_length = 3
truncation_symbol = "…/"
style = "bold cyan"
format = '[\[](dimmed) [$path]($style) [\]](dimmed) '

[git_branch]
format = '[\[](dimmed) [$symbol$branch]($style) [\]](dimmed) '
symbol = ""
style = "italic purple"

[git_status]
format     = '[$all_status$ahead_behind]($style)'
style      = "bold red"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = "✗ "
up_to_date = ""
untracked  = "? "
modified   = "✱ "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""

[nodejs]
format    = '[\[](dimmed) [$symbol($version )]($style) [\]](dimmed) '
symbol    = " "
version_format = "v${raw}"
style     = "bold green"
detect_extensions = ["js", "mjs", "cjs", "ts", "mts", "cts", "jsx", "tsx", "node"]
detect_files = ["package.json", ".node-version", ".nvmrc"]

[python]
format    = '[\[](dimmed) [$symbol($version )]($style) [\]](dimmed) '
symbol    = " "
style     = "bold yellow"
python_binary = ["python3", "python"]
detect_extensions = ["py", "pyi"]
detect_files = ["pyproject.toml", "requirements.txt", "Pipfile", "poetry.lock", ".python-version"]

[battery]
format           = '[\[](dimmed) [$percentage]($style) [\]](dimmed) '

[[battery.display]]
threshold = 20
style     = "bold red"

[[battery.display]]
threshold = 50
style     = "bold yellow"

[[battery.display]]
threshold = 100
style     = "bold green"

[custom.net]
command = "~/.config/starship/nettype.sh"
format   = '[\[](dimmed) [$output]($style) [\]](dimmed) '
shell    = "bash"
style    = "bold blue"
when     = true

[time]
disabled     = false
format       = '[\[](dimmed) [$time]($style) [\]](dimmed) '
time_format  = "%H:%M"
style        = "bold magenta"
